steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/coba-coba-project-407404/teras-backend', '.']
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/coba-coba-project-407404/teras-backend']
  # Create release in Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: 
      [
        "beta", "deploy", "releases", "create", "rel-${SHORT_SHA}a",
        "--delivery-pipeline", "teras-backend-pipeline",
        "--region", "asia-southeast2",
        "--annotations", "commitId=${REVISION_ID}",
        "--images", "teras-backend=gcr.io/coba-coba-project-407404/teras-backend"
      ]
