package com.bangkit.teras_app.model

val listProvince = listOf(
    Pair("Aceh", "Aceh"),
    Pair("Sumatera Utara", "Sumatera Utara"),
    Pair("Sumatera Barat", "Sumatera Barat"),
    Pair("Riau", "Riau"),
    Pair("Jambi", "Jambi"),
    Pair("Sumatera Selatan", "Sumatera Selatan"),
    Pair("Bengkulu", "Bengkulu"),
    Pair("Lampung", "Lampung"),
    Pair("Kepulauan Bangka", "Kepulauan Bangka"),
    Pair("Kepulauan Riau", "Kepulauan Riau"),
    Pair("Jakarta", "Jakarta"),
    Pair("Jawa Barat", "Jawa Barat"),
    Pair("Jawa Tengah", "Jawa Tengah"),
    Pair("Yogyakarta", "Yogyakarta"),
    Pair("Jawa Timur", "Jawa Timur"),
    Pair("Banten", "Banten"),
    Pair("Bali", "Bali"),
    Pair("Nusa Tenggara Barat", "Nusa Tenggara Barat"),
    Pair("Nusa Tenggara Timur", "Nusa Tenggara Timur"),
    Pair("Kalimantan Barat", "Kalimantan Barat"),
    Pair("Kalimantan Tengah", "Kalimantan Tengah"),
    Pair("Kalimantan Selatan", "Kalimantan Selatan"),
    Pair("Kalimantan Timur", "Kalimantan Timur"),
    Pair("Kalimantan Utara", "Kalimantan Utara"),
    Pair("Sulawesi Utara", "Sulawesi Utara"),
    Pair("Sulawesi Tengah", "Sulawesi Tengah"),
    Pair("Sulawesi Selatan", "Sulawesi Selatan"),
    Pair("Sulawesi Tenggara", "Sulawesi Tenggara"),
    Pair("Sulawesi Barat", "Sulawesi Barat"),
    Pair("Gorontalo", "Gorontalo"),
    Pair("Maluku", "Maluku"),
    Pair("Maluku Utara", "Maluku Utara"),
    Pair("Papua Barat", "Papua Barat"),
    Pair("Papua", "Papua")
)